### ISSUE TITLE
[1.19.2] Unable to craft the backpacks. 

### ISSUE THREAD

**Issue by jakeklong** [kwpugh/simple_backpack#44]
I'm unable to craft the backpacks, the bundles and crafting on the go works though. I can see the backpacks with Roughly Enough Items, but even when I try cheating them into my inventory, it just tells me it's unable to add the item.

I'm on 1.19.2 and I'm on the current fabric loader with fabric api up to date.

**Comment by kwpugh** [comment]
Can you post a copy of your latest system log please?

**Comment by jakeklong** [comment]
here is the log you requested, i appreciate it. it worked as is in 1.19.1, its a new world since the update.
[latest.log](https://github.com/kwpugh/simple_backpack/files/9295581/latest.log)

--thank you for the help, Katelyn.

**Comment by jakeklong** [comment]
i believe i uploaded the wrong log. here is one with the most recent crash. sorry about that
[latest.log](https://github.com/kwpugh/simple_backpack/files/9305918/latest.log)

**Comment by jakeklong** [comment]
somehow after updating both my world and my server, the server reverted itself to 1.19.2.
your mod works flawlessly and im an idiot. sometimes you look past the simple things. i apologize. cheers!

**Comment by kwpugh** [comment]
no prob, enjoy.
