### ISSUE TITLE
[1.19.1] Backpack contents missing after upgrade

### ISSUE THREAD

**Issue by dranorter** [kwpugh/simple_backpack#45]
I'm preparing to upgrade a server from 1.18.1 to 1.19.1, and in my first test, I found that backpack contents have disappeared. Backpacks show as having "1 nbt tag"; and then, if I add items to the backpack, it retains the new items and has "2 nbt tags". Was there a change to the formatting of the data tags?

I'm directly switching from mod version 1.2.30 to 1.3.19. I'll reply more here when I have more information.

**Comment by kwpugh** [comment]
there wasn't any significant changes since the 1.17 to 1.18 changes.   that said, updating a full version is never recommended and I cannot support that.

**Comment by dranorter** [comment]
No problem, I'm not asking for support. I'll reply more if I figure out a
fix, but you can close the issue if you prefer.

**Comment by dranorter** [comment]
It's a capitalization issue! The old NBT data for some reason lists backpack contents under "items", and data from after updating lists it under "Items". I'm not sure what the most direct fix is yet but that's the root cause.

**Comment by kwpugh** [comment]
that is nothing I control, perhaps the fabric or mojang folks change that in the update.  I just call the net methods and give it a name "backpack" and it does the magic.   Thanks for letting me know.
