### ISSUE TITLE
config option to enable previous method of opening backpack?

### ISSUE THREAD

**Issue by Skeithh** [kwpugh/simple_backpack#47]
I find the new method of opening the backpack highly inconvenient and I can't find any settings to set it back to the old method, can we have that? I don't really see why your backpack has to be in the offhand to be opened, especially as the mod page advertises itself as "no hotkeys". Making you have to swap it to offhand immediately goes against the "simple" aspect, as now you have to press a hotkey before getting to open it.

**Comment by kwpugh** [comment]
What version of backpack are you using?  1.18.2 has a config option to turn off and 1.9.2 doesn't have the off hand thing anymore.

**Comment by Skeithh** [comment]
ohh woops, was completely blind while going through my files there- found the configs hahah. Will close the ticket d:

**Comment by kwpugh** [comment]
enjoy.
