### ISSUE TITLE
simple bundle：container info does not exist on the server

### ISSUE THREAD

**Issue by Ervoconite** [kwpugh/simple_backpack#48]
![image](https://user-images.githubusercontent.com/56382289/195983511-b53a9445-8ef8-46a6-b873-551ccc8b9f08.png)
internal error：container info does not exist on the server

**Comment by kwpugh** [comment]
What version of Simple Bundle?

**Comment by Ervoconite** [comment]
It seems like not related to this mod, thanks

**Comment by VashaTS** [comment]
I got the same message when trying to craft items on Prrtable crafter, usung NEI "+" button, "move items to crafting grid" function.
Version SimpleBackpack_Fabric-1.19.1-1.3.18.jar
Maybe its better rephrased as: Can you make Portable crafter work with NEI & clones the same way that vanilla crafting table does?
