### ISSUE TITLE
1.20+ Update

### ISSUE THREAD

**Issue by Harvle** [kwpugh/simple_backpack#59]
Hi, sorry for pestering but is there an udate on when or if this mod will be updated to 1.20+, as i use this in so many worlds and servers, i'd love to see it updated.

I did try downloading the source to get it compile myself in 1.20 but it seems a bit over my head, sadly i don't know too much about java.

Thank you!

**Comment by random-j-farmer** [comment]
My forked version seems to work https://github.com/random-j-farmer/simple_backpack

You can build that branch for 1.20.1

    # you need git and a jdk17 in your path
    git clone https://github.com/random-j-farmer/simple_backpack
    cd simple_backpack
   ./gradlew publishToMavenLocal
   # the jar is in the build/jars directory

**Comment by random-j-farmer** [comment]
@kwpugh if you would like a pull request I would be happy to make one - I did not know what branch to use (1.20.1 does not exist yet and it would not let me choose that)

**Comment by Harvle** [comment]
Thanks, just compiled it myself and it seems to work fine in my world, no missing items and they're all doing as they should!

**Comment by mike1000195** [comment]
random-j-farmer's method of using gradle to recompile it for 1.20.1 worked flawlessly. why not just upload the mod real quick since the hard work was already done so that way people can use it? i've been waiting this whole time to update to 1.20.1 because this was the only mod left to update, and im glad someone found a workaround. or maybe give him authority to upload it to your curseforge page? not entirely sure how all that works, but since there are working versions of this mod, people should have it and be able to use it

**Comment by AryonLegacy** [comment]
can someone just drop a download link for jar? i tried building but just get error...

**Comment by AryonLegacy** [comment]
> random-j-farmer's method of using gradle to recompile it for 1.20.1 worked flawlessly. why not just upload the mod real quick since the hard work was already done so that way people can use it? i've been waiting this whole time to update to 1.20.1 because this was the only mod left to update, and im glad someone found a workaround. or maybe give him authority to upload it to your curseforge page? not entirely sure how all that works, but since there are working versions of this mod, people should have it and be able to use it

can you help me?

**Comment by Fleepe** [comment]
Hallelujah, he came and updated the mod!
legacy.curseforge.com/minecraft/mc-mods/simple-backpack-fabric/files/5118160

**Comment by kwpugh** [comment]
I manually updated, the source code on GitHub is for read-only person, I keep the most recent code locally.

Thanks anyway for the work.
