### ISSUE TITLE
Add cloth-config dependency to fabric.mod.json

### ISSUE THREAD

**Issue by Poopooracoocoo** [kwpugh/simple_backpack#64]
I also noticed that it's not present in the CurseForge dependencies of newer releases either: https://www.curseforge.com/minecraft/mc-mods/simple-backpack-fabric/files/5118160/dependencies

Made this after seeing https://www.reddit.com/r/fabricmc/comments/1balig2/help_me_plss/

**Comment by kwpugh** [comment]
fixed
